config/routes.rb
Rails.application.routes.draw do
   root to: 'tasks#index'
   resources :tasks
   
   
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
   
   
     get 'signup', to: 'users#new'
  resources :users, only: [ :new, :create]
  

 resources :tasks,  only: [:create, :destroy,:edit,:update, :show,:new]



end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
    belongs_to :user
    validates :content, presence: true, length: { maximum: 255 }
  validates :status, presence: true, length: { maximum: 10 }
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email.downcase! }
  validates :name, presence: true, length: { maximum: 50 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  
  has_many :tasks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  include SessionsHelper

  private

  def require_user_logged_in
    unless logged_in?
      redirect_to login_url
    end
  end
  

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    @new_user = User.new
  end

  def create
    email = params[:session][:email].downcase
    password = params[:session][:password]
    if login(email, password)
      flash[:success] = 'ログインに成功しました。'
      redirect_to root_url
    else
      flash.now[:danger] = 'ログインに失敗しました。'
      render :new
    end
  end

 
  def destroy
    session[:user_id] = nil
    flash[:success] = 'ログアウトしました。'
    redirect_to login_path
  end

  private

  def login(email, password)
    @user = User.find_by(email: email)
    if @user && @user.authenticate(password)
      # ログイン成功
      session[:user_id] = @user.id
      return true
    else
      # ログイン失敗
      return false
    end
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
    before_action :require_user_logged_in
      before_action :currect_user, only: [:destroy,:update,:edit,:show]
        # before_action :set_task, only: [ :edit, :update , :destroy]







    # before_action :only: [:show, :edit, :update, :destroy ,:index]

  def index

    # @tasks = Task.all
      @task = current_user.tasks.build  # form_with 用
      @tasks = current_user.tasks.order(id: :desc).page(params[:page])
       @task1 = current_user.tasks.find_by(id: params[:id])
       



    
  end



   
  
  def show
        @task1 = Task.find(params[:id])

    
    @task = current_user.tasks.find_by(id: params[:id])
    

    
    




       
  end

  def new
      @task = current_user.tasks.build  # form_with 用
      @tasks = current_user.tasks.order(id: :desc).page(params[:page])
    

  
  end

  def create
    @task = current_user.tasks.build(task_params)
    if @task.save
      flash[:success] = 'メッセージを投稿しました。'
      redirect_to root_url
    else
      @tasks = current_user.tasks.order(id: :desc).page(params[:page])
      flash.now[:danger] = 'メッセージの投稿に失敗しました。'
      render 'tasks/index'
    end
  end

  def edit
    
      
  end

  def update
    

    if @task.update(task_params)
      flash[:success] = 'タスク は正常に更新されました'
      redirect_to @task
    else
      flash.now[:danger] = 'タスク は更新されませんでした'
      render :edit
    end
  end

 def destroy

    @task.destroy
    flash[:success] = 'メッセージを削除しました。'
    redirect_to root_url
 end



  private
  
  def currect_user
    @task = current_user.tasks.find_by(id: params[:id])
    unless @task
      redirect_to root_url
    end
  end
  
  def task_params
    params.require(:task).permit(:content, :status,:user_id)
  end
  
  def set_task
    @task = Task.find(params[:id])
        # @task = current_user.tasks.find_by(id: params[:id])


  end
  
  

  

  
end

  
  

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_user_logged_in, only: [:index, :show]
  

    def new

    @user = User.new

    end



  def create
    @user = User.new(user_params)

    if @user.save
      flash[:success] = 'ユーザを登録しました。'
      redirect_to root_url
    else
      flash.now[:danger] = 'ユーザの登録に失敗しました。'
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
   
     def current_user
    @current_user ||= User.find_by(id: session[:user_id])
   end

  def logged_in?
    !!current_user
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div id="error_explanation" class="alert alert-warning">
    <ul class="mb-0">
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_flash_messages.html.erb
<% flash.each do |task_type, task| %>
  <div><%= task %></div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>KadaiTasklist</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
        <div class="container">
      <%= render 'layouts/flash_messages' %>
    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_with(model:task, local: true) do |f| %>
  <% if task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(task.errors.count, "error") %> prohibited this message from being saved:</h2>

      <ul>
        <% task.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>


 <%= f.label :status, '状態' %>
  <%= f.text_field :status %>
  <%= f.label :content, 'タスク' %>
  <%= f.text_field :content %>

  <%= f.submit 'Post' %>
<% end %>

app/views/tasks/_indexpreview.html.erb
<ul class="list-unstyled">
    <% tasks.each do |task| %>

 <div>
          <%= link_to task.content, task_path(task) %> 
        </div>
       
           <p></p>
          <p>状態:<%= task.status %></p>
          <p>タイトル:<%= task.content %></p>
          <%= link_to '一覧に戻る', tasks_path %>

                       <%= link_to "Edit", edit_task_path(task),   class: 'btn btn-danger btn-sm' %>

                      <%= link_to "Delete", task,method: :delete, data: { confirm: "You sure?" }, class: 'btn btn-danger btn-sm' %>

    </li>
  <% end %>
  <%= paginate tasks %>
</ul>

app/views/tasks/_test.erb
<ul class="list-unstyled">
  <% @tasks.each do |task| %>
    <li class="media mb-3">
      <div class="media-body">
        <div>
          <%= link_to task.content, task_path(task) %> <span class="text-muted">posted at <%= task.created_at %></span>
        </div>
        <div>
           <p></p>
          <p><%= task.status %></p>
          <p><%= task.content %></p>
        </div>
        <div>
            <%= link_to "Edit", edit_task_path(task),   class: 'btn btn-danger btn-sm' %>
            <%= link_to "Delete", task, method: :delete, data: { confirm: "You sure?" }, class: 'btn btn-danger btn-sm' %>
        <% end %>
      </div>
      </div>
    </li>
  <% end %>
  <%= paginate task %>
</ul>
<% end %>

app/views/tasks/edit.html.erb
<h1>id: <%= @task.id %> タスク</h1>

<%= render 'form', task: @task %>
<%= link_to '一覧に戻る', tasks_path %>

app/views/tasks/index.html.erb
<h1>タスク一覧</h1>












<!--<ul>-->

<!--  <% @tasks.each do |task| %>-->

<!--        <li><%= link_to task.user, task %> : <%= task.status %> &gt;   <%= task.content %></li>-->



<!--  <% end %>-->

<!--</ul>-->



      <%= render 'tasks/indexpreview', tasks: @tasks %>




<%= link_to '新規タスクの投稿', new_task_path %>



              <li class="dropdown-item"><%= link_to 'Logout', logout_path, method: :delete %></li>

app/views/tasks/new.html.erb
<h1>タスク新規作成ページ</h1>

  <%= form_with(model: @task, local: true) do |f| %>
        <div class="form-group">
            <%= f.label :content, 'タスク' %>

           <%= f.text_field :content, class: 'form-control', rows: 5 %>
          <%= f.label :status, '状態' %>

            <%= f.text_field :status, class: 'form-control', rows: 5 %>

        </div>
        <%= f.submit 'POST',  class: 'btn btn-primary btn-block' %>
      <% end %>    



<%= link_to '一覧に戻る', tasks_path %>

app/views/tasks/show.html.erb
<h1> タスクの詳細ページ</h1>



   
<ul class="list-unstyled">

 <div>
        </div>
       

          <p>状態:<%= @task1.status %></p>
          <p>タイトル:<%= @task1.content %></p>
          <%= link_to '一覧に戻る', tasks_path %>

 <%= link_to "Edit", edit_task_path(@task),   class: 'btn btn-danger btn-sm' %>
  <%= link_to "Delete", @task1 ,method: :delete, data: { confirm: "You sure?" }, class: 'btn btn-danger btn-sm' %>
                      
                      



    </li>
</ul>

app/views/users/new.html.erb
<div class="text-center">
  <h1>Sign up</h1>
</div>

<div class="row">
  <div class="col-sm-6 offset-sm-3">

    <%= form_with(model: @user, local: true) do |f| %>
     <%= render 'layouts/error_messages', model: f.object %>
      
      <div class="form-group">
        <%= f.label :name, 'Name' %>
        <%= f.text_field :name, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :email, 'Email' %>
        <%= f.email_field :email, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :password, 'Password' %>
        <%= f.password_field :password, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :password_confirmation, 'Confirmation' %>
        <%= f.password_field :password_confirmation, class: 'form-control' %>
      </div>

      <%= f.submit 'Sign up', class: 'btn btn-primary btn-block' %>
    <% end %>
  </div>
</div>